steps:
  # 1. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    args:
      - "build"
      - "--build-arg"
      - "VITE_CONVEX_URL=${_VITE_CONVEX_URL}"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/kanban-board/${_SERVICE_NAME}:${_COMMIT_SHA}"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/kanban-board/${_SERVICE_NAME}:latest"
      - "."

  # 2. Push image with commit SHA tag
  - name: "gcr.io/cloud-builders/docker"
    id: "Push to Artifact Registry"
    waitFor: ["Build Docker Image"]
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/kanban-board/${_SERVICE_NAME}:${_COMMIT_SHA}"

  # 3. Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    id: "Push latest tag"
    waitFor: ["Build Docker Image"]
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/kanban-board/${_SERVICE_NAME}:latest"

  # 4. Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy to Cloud Run"
    waitFor: ["Push latest tag"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
          gcloud run deploy ${_SERVICE_NAME} \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/kanban-board/${_SERVICE_NAME}:${_COMMIT_SHA} \
            --service-account progressive-reader-bvt-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-secrets /secrets/env.json=app-config:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars APP_ENV=${_ENVIRONMENT} \
            --vpc-connector floof-connector \
            --vpc-egress private-ranges-only

substitutions:
  _VITE_CONVEX_URL: ''
  _SERVICE_NAME: 'kanban-board'
  _COMMIT_SHA: '${COMMIT_SHA}'
  _ENVIRONMENT: 'production'

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/kanban-board/${_SERVICE_NAME}:${_COMMIT_SHA}"

timeout: 1200s